rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {

    // 1. Allows any authenticated user to read from the 'admins' collection.
    // This is necessary for the app to check if the user is an admin.
    match /admins/{userId} {
      allow read: if request.auth != null;
      allow write: if false;
    }

    // 2. Allows authenticated users to create and read their own user documents.
    // 'create' is allowed because the `registerUser` function creates a document if one does not exist.
    match /users/{userId} {
      allow read, create: if request.auth.uid == userId;
      allow update, delete: if false;
    }

    // 3. Allows any user (even unauthenticated) to read and write public messages.
    // This is for the `public/messages` collection.
    match /public/messages/{messageId} {
      allow read, write: if true;
    }
  }
}
